version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fraudgraph"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oyu9dgdnzev2"
s3_prefix = "fraudgraph"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
